export const QUESTION_SLUGS_COOKIES = 'doneQuestionsSlugs'

export const TOPIC_TAGS = [
  'Monotonic Stack',
  'Breadth-First Search',
  'Stack',
  'Greedy',
  'Array',
  'Matrix',
  'Two Pointers',
  'Depth-First Search',
  'Backtracking',
  'Combinatorics',
  'Sliding Window',
  'String Matching',
  'Binary Search',
  'Tree',
  'Bit Manipulation',
  'Merge Sort',
  'Divide and Conquer',
  'Heap (Priority Queue)',
  'Linked List',
  'Trie',
  'Binary Search Tree',
  'Memoization',
  'Hash Table',
  'Simulation',
  'Math',
  'Recursion',
  'Binary Tree',
  'Dynamic Programming',
  'Sorting',
  'String',
]
