export const QUESTION_SLUGS_COOKIES = 'doneQuestionsSlugs'

export const TAG_HIERARCHY = [
  'Breadth-First Search',
  'Heap (Priority Queue)',
  'String Matching',
  'Trie',
  'Dynamic Programming',
  'Merge Sort',
  'Binary Search',
  'Monotonic Stack',
  'Sliding Window',
  'Binary Search Tree',
  'Two Pointers',
  'Depth-First Search',
  'Hash Table',
  'Backtracking',
  'Tree',
  'Combinatorics',
  'Linked List',
  'Binary Tree',
  'Bit Manipulation',
  'Stack',
  'Greedy',
  'Divide and Conquer',
  'Recursion',
  'Matrix',
  'Sorting',
  'Simulation',
  'Memoization',
  'String',
  'Array',
  'Math',
]
